# -*- coding: utf-8 -*-
"""
CDSS audit-log telemetry analytics (post-deployment monitoring, JAMIA 2024).

Reads the PHI-safe JSONL audit log written by ClinicalAdvisor(audit_log=...)
and reports: volume by day, mode/priority/confidence distributions,
rule-firing frequencies, alert burden, red-flag surveillance.

Usage:
  python code/cdss_audit_log_analytics.py [path/to/cdss_advice_log.jsonl]

If no log exists yet, a demonstration log is generated by replaying the
301-admission real cohort through the CDSS (PHI-safe: no identifiers stored),
then analysed — this doubles as a telemetry dry-run.
"""
import sys, os, json, collections
import pandas as pd

sys.path.insert(0, r'D:\research\人脸识别营养\传染科\deployment')
sys.stdout.reconfigure(encoding='utf-8')
BASE = r'D:\research\人脸识别营养\传染科'
DEFAULT_LOG = os.path.join(BASE, 'deployment', 'audit', 'cdss_advice_log.jsonl')


def load_records(path):
    recs = []
    with open(path, encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    recs.append(json.loads(line))
                except Exception:
                    continue
    return recs


def demo_replay(log_path):
    """Replay the 301-admission cohort to create a demonstration audit log."""
    import importlib
    if 'clinical_advisor' in sys.modules:
        del sys.modules['clinical_advisor']
    import clinical_advisor as ca
    src = pd.read_excel(os.path.join(BASE, '按文本_合并后的肝炎患者问卷.xlsx'))
    LAB_MAP = {
        'tbil': '26、总胆红素值（umol/L）', 'ibil': '27、间接胆红素值（umol/L）',
        'dbil': '28、直接胆红素值（umol/L）', 'alt': '31、ALT丙氨酸氨基转移酶（IU/L）',
        'ast': '32、AST门冬氨酸氨基转移酶（IU/L）', 'ggt': '33、GGT谷氨酰转肽酶（IU/L）',
        'alp': '34、ALP碱性磷酸酶（IU/L）', 'inr': '36、INR 国际标准化比值',
        'albumin': '42、白蛋白（g/L）',
    }
    advisor = ca.ClinicalAdvisor(lang='cn', audit_log=log_path)
    n = 0
    for _, r in src.iterrows():
        labs = {}
        for k, col in LAB_MAP.items():
            v = pd.to_numeric(r.get(col), errors='coerce')
            if pd.notna(v):
                labs[k] = float(v)
        nrs = pd.to_numeric(r.get('14、NRS2002评分'), errors='coerce')
        nutrition = ({'nrs2002': float(nrs)}
                     if pd.notna(nrs) and 0 <= nrs <= 7 else None)
        advisor.advise(None, lab_values=labs or None,
                       diagnosis=str(r.get('3、入院主要诊断') or '') or None,
                       nutrition=nutrition)
        n += 1
    print(f'[demo] replayed {n} admissions -> {log_path}')
    return n


def analyse(recs):
    df = pd.DataFrame(recs)
    df['ts'] = pd.to_datetime(df.get('timestamp'), errors='coerce')
    n = len(df)
    print(f'\n{"=" * 70}\n  CDSS AUDIT LOG TELEMETRY — {n} advice events\n{"=" * 70}')

    if 'ts' in df and df['ts'].notna().any():
        daily = df.set_index('ts').resample('D').size()
        print('\n  Events per day:')
        for day, cnt in daily.items():
            print(f'    {day.date()}  {cnt}')

    for col in ['mode', 'alert_priority', 'confidence', 'severity',
                'nutrition_state']:
        if col in df:
            print(f'\n  {col} distribution: {df[col].value_counts().to_dict()}')

    if 'rule_ids' in df:
        rule_freq = collections.Counter(
            rid for lst in df['rule_ids'] if isinstance(lst, list) for rid in lst)
        print('\n  Top-15 rule firing frequencies (surveillance view):')
        for rid, cnt in rule_freq.most_common(15):
            print(f'    {rid:32s} {cnt:5d}  ({100 * cnt / n:5.1f}% of events)')
        rf_events = df['rule_ids'].apply(
            lambda lst: any(str(r).startswith('REDFLAG_')
                            for r in (lst or []))).sum()
        print(f'\n  Red-flag events: {rf_events}/{n} ({100 * rf_events / n:.1f}%)')

    if 'n_rules' in df:
        print(f"\n  Alert burden: mean={df['n_rules'].mean():.1f} "
              f"median={df['n_rules'].median():.0f} max={df['n_rules'].max()}")
    if 'department' in df:
        print(f"\n  Department usage: {df['department'].value_counts().to_dict()}")
    if 'lang' in df:
        print(f"  Language usage: {df['lang'].value_counts().to_dict()}")


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_LOG
    if not os.path.exists(path) or os.path.getsize(path) == 0:
        print(f'Audit log absent/empty: {path}')
        print('Generating demonstration log from the 301-admission cohort replay...')
        os.makedirs(os.path.dirname(path), exist_ok=True)
        demo_replay(path)
    recs = load_records(path)
    if recs:
        analyse(recs)
        out = os.path.join(BASE, 'results', 'face_v4_manuscript_delivery',
                           'tables', 'CDSS_AUDIT_LOG_TELEMETRY.csv')
        pd.DataFrame(recs).to_csv(out, index=False)
        print(f'\nSaved: {out}')
    else:
        print('No valid records to analyse.')


if __name__ == '__main__':
    main()
